name: Deploy EC2

on: [push]
      # paths-ignore:
      #   - 'README.md'
      #   - 'LICENSE.md'
  
jobs:
    deploy-to-ec2:
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout do Repositorio
          uses: actions/checkout@v3
  
        - name: Python
          uses: actions/setup-python@v3
          with:
            python-version: '3.x'
  
        - name: Instalando Dependencias
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
  
        - name: Configurando Credenciais EC2
          run: |
            echo "${{ secrets.EC2_PRIVATE_KEY }}" > /tmp/ec2-keypair.pem
            chmod 600 /tmp/ec2-keypair.pem
    
        - name: Configurando credenciais de User
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: 'us-east-1'
          run: |
            
            echo "Instalando o Git"
            sudo yum install git -y
            git pull origin main
            
            echo "Criando ambiente virtual python"
            python3 -m venv venv
            source venv/bin/activate

            echo "Instalando as dependências do projeto"
            pip install -r requirements.txt

            echo "Iniciando Gunicorn para servir o Flask App...""
            nohup gunicorn --bind 0.0.0.0:5000 app:app > gunicorn.log 2>&1 & disown
            
            # Mensagem de Sucesso do Deploy
            echo "Deploy completado com sucessso!"
            EOF