name: Deploy EC2

on: [push]
      # paths-ignore:
      #   - 'README.md'
      #   - 'LICENSE.md'
  
jobs:
    deploy-to-ec2:
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout do Repositorio
          uses: actions/checkout@v3
  
        - name: Python
          uses: actions/setup-python@v3
          with:
            python-version: '3.x'
  
        - name: Instalando Dependencias
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
  
        - name: Instalar SSH Key
          uses: webfactory/ssh-agent@v0.5.3
          with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
  
        - name: Deploy no Amazon Linux EC2
          run: |
            ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_IP }} << 'EOF'
            cd /home/ec2-user/app
            
            echo "Instalando o Git"
            sudo yum install git -y
            git pull origin main
            
            echo "Criando ambiente virtual python"
            python3 -m venv venv
            source venv/bin/activate

            echo "Instalando as dependências do projeto"
            pip install -r requirements.txt

            echo "Iniciando Gunicorn para servir o Flask App...""
            nohup gunicorn --bind 0.0.0.0:5000 app:app > gunicorn.log 2>&1 & disown
            
            # Mensagem de Sucesso do Deploy
            echo "Deploy completado com sucessso!"
            EOF